### ISSUE TITLE
Improve Header. Add Minisuper logo and put it at the center of the page.

### ISSUE THREAD

**Issue by alayor** [minisuperapp/minisuper-customer-webapp-ui#11]
Improve Header. Add Minisuper logo and put it at the center of the page.

![logo](https://user-images.githubusercontent.com/2164371/50801183-de96c180-12a0-11e9-8290-7268fa0dde98.png)

**Comment by YojanR** [comment]
![sin titulo](https://user-images.githubusercontent.com/36801510/50812853-f3dc1200-12d9-11e9-95af-33728cfd7d16.png)

**Comment by YojanR** [comment]
![sin titulo](https://user-images.githubusercontent.com/36801510/50812921-40bfe880-12da-11e9-9bbd-bd09a2577889.png)

**Comment by alayor** [comment]
Muy bien, aunque se ve un tanto pixeleado.
Deja le pido a la diseñadora si me puede entregar el logotipo con los color invertidos.

**Comment by YojanR** [comment]
blob:https://web.whatsapp.com/d44577ed-d498-4d5a-ace1-67140248ecb0

**Comment by YojanR** [comment]
Asi queda con el fondo blanco

![whatsapp image 2019-01-08 at 00 18 19](https://user-images.githubusercontent.com/36801510/50813180-2f2b1080-12db-11e9-8a3b-856ca8372f64.jpeg)

Y así queda con el fondo verde y colores invertidos

![whatsapp image 2019-01-08 at 00 14 19](https://user-images.githubusercontent.com/36801510/50813203-4669fe00-12db-11e9-9b6c-23df64d028bd.jpeg)
